---
kind: Template
apiVersion: template.openshift.io/v1
labels:
  app: "${NAME}"
  build: "${NAME}"
  template: "${NAME}-bc-template"
metadata:
  name: n8n-bc
objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: "${NAME}"
      namespace: "${N8N_IMAGE_NAMESPACE}"
    spec:
      lookupPolicy:
        local: false
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: "${NAME}"
      namespace: "${N8N_IMAGE_NAMESPACE}"
      labels:
        app: "${NAME}"
        build: "${NAME}"
        buildconfig: "${NAME}"
    spec:
      nodeSelector: null
      successfulBuildsHistoryLimit: 3
      failedBuildsHistoryLimit: 3
      completionDeadlineSeconds: 600
      source:
        type: Git
        git:
          uri: "${GIT_URI}"
          ref: "${GIT_REF}"
        contextDir: "${CONTEXT_DIR}"
      strategy:
        type: Docker
        dockerStrategy:
          # Do not specify 'from' so the Dockerfile's own FROM is used
          dockerfilePath: "${DOCKERFILE_PATH}"
      output:
        to:
          kind: ImageStreamTag
          name: "${NAME}:latest"
      resources:
        limits:
          cpu: 1400m
          memory: 3Gi
        requests:
          cpu: 500m
          memory: 512Mi
      triggers:
        - type: ConfigChange
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.
    required: true
    value: n8n
  - name: N8N_IMAGE_NAMESPACE
    displayName: N8N Image Namespace
    description: The namespace where the N8N image is stored.
    required: true
    value: bf5ef6-tools
  - name: GIT_URI
    displayName: Git Repository URL
    required: true
    value: https://github.com/bcgov/put.git
  - name: GIT_REF
    displayName: Git Reference (branch/tag/commit)
    required: true
    value: main
  - name: CONTEXT_DIR
    displayName: Context Directory (relative to repo root)
    required: false
    value: ""
  - name: DOCKERFILE_PATH
    displayName: Dockerfile Path (relative to context dir)
    required: true
    value: containers/workflow/Dockerfile