apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  monitoring:
    pgmonitor:
      exporter:
        image: image-registry.openshift-image-registry.svc:5000/e31b6b-dev/crunchy-postgres-exporter:ubi8-5.0.4-0
  image: image-registry.openshift-image-registry.svc:5000/e31b6b-dev/crunchy-postgres:centos8-14.2-0
  postgresVersion: 14
  instances:
    - name: ha1
      replicas: 3
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 5Gi
        storageClassName: netapp-block-standard
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: hippo
                  postgres-operator.crunchydata.com/instance-set: ha1
  users:
    - name: hippo
      databases:
        - hippo
    - name: hippo-api
      options: "CREATEROLE"
    - name: postgres
  backups:
    pgbackrest:
      global:
        repo1-retention-full: "2"
      image: image-registry.openshift-image-registry.svc:5000/e31b6b-dev/crunchy-pgbackrest:ubi8-2.40-1
      repos:
      - name: repo1
        schedules:
          # Full backup every day at 8:00am UTC
          full: "0 8 * * *"
          # Incremental backup every 4 hours, except at 8am UTC (when the full backup is running)
          incremental: "0 0,4,12,16,20 * * *"
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 5Gi
            storageClassName: netapp-file-backup
  proxy:
    pgBouncer:
      config:
        global:
          client_tls_sslmode: disable
      image: image-registry.openshift-image-registry.svc:5000/e31b6b-dev/crunchy-pgbouncer:centos8-1.16-1
      replicas: 2
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: hippo
                  postgres-operator.crunchydata.com/role: pgbouncer
