apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - services.yaml
  - routes.yaml
  - postgresql-statefulset.yaml
  - redis-statefulset.yaml
  - n8n-deployment.yaml
  - n8n-worker-deployment.yaml
  - n8n-webhook-deployment.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
