apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/part-of: {{ .Values.name }}-app
    template: {{ .Values.name }}-dc-template
  name: allow-all-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingress:
  - {}
  podSelector: {}
  policyTypes:
  - Ingress
