apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: netapp-file-standard
    volume.beta.kubernetes.io/storage-provisioner: csi.trident.netapp.io
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/part-of: {{ .Values.name }}-app
    template: {{ .Values.name }}-dc-template
  name: {{ .Values.name }}-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc_size }}
  storageClassName: netapp-file-standard
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: netapp-file-standard
    volume.beta.kubernetes.io/storage-provisioner: csi.trident.netapp.io
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/part-of: {{ .Values.name }}-app
    template: {{ .Values.name }}-dc-template
  name: redis-{{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis_pvc_size }}
  storageClassName: netapp-file-standard
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: netapp-file-standard
    volume.beta.kubernetes.io/storage-provisioner: csi.trident.netapp.io
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/part-of: {{ .Values.name }}-app
    template: {{ .Values.name }}-dc-template
  name: postgresql-{{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.psql_pvc_size }}
  storageClassName: netapp-file-standard
  volumeMode: Filesystem
