apiVersion: v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/balance: leastconn
    haproxy.router.openshift.io/timeout: 1d
    openshift.io/host.generated: "true"
    router.openshift.io/cookie_name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/part-of: {{ .Values.name }}-app
    template: {{ .Values.name }}-dc-template
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Values.name }}-{{ .Values.namespace }}.apps.{{ .Values.cluster_name }}.devops.gov.bc.ca
  path: /
  port:
    targetPort: 5678-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.name }}
  wildcardPolicy: None
---
apiVersion: v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/balance: leastconn
    haproxy.router.openshift.io/timeout: 1d
    openshift.io/host.generated: "true"
    router.openshift.io/cookie_name: {{ .Values.name }}-webhook"
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/part-of: {{ .Values.name }}-app
    template: {{ .Values.name }}-dc-template
  name: {{ .Values.name }}-webhook
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Values.name }}-{{ .Values.namespace }}.apps.{{ .Values.cluster_name }}.devops.gov.bc.ca
  path: /webhook
  port:
    targetPort: 5678-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.name }}-webhook
  wildcardPolicy: None
