apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-encryption_key: '{.data[encryption-key]}'
    template.openshift.io/expose-password: '{.data[password]}'
    template.openshift.io/expose-username: '{.data[username]}'
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/part-of: {{ .Values.name }}-app
    template: {{ .Values.name }}-dc-template
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
stringData:
  encryption-key: {{ .Values.n8n_encryption_key }}
  password: {{ .Values.n8n_password }}
  username: {{ .Values.n8n_user }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  app: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/part-of: {{ .Values.name }}-app
    template: {{ .Values.name }}-dc-template
  name: postgresql-{{ .Values.name }}
  namespace: {{ .Values.namespace }}
stringData:
  database-name: {{ .Values.name }}
  database-password: {{ .Values.database_password }}
  database-user: {{ .Values.name }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-password: '{.data[''database-password'']}'
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/part-of: {{ .Values.name }}-app
    template: {{ .Values.name }}-dc-template
  name: redis-{{ .Values.name }}
  namespace: {{ .Values.namespace }}
stringData:
  database-password: {{ .Values.redis_database_password }}
type: Opaque
