apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Values.name }}
    app.kubernetes.io/part-of: {{ .Values.name }}-app
    template: {{ .Values.name }}-dc-template
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: 5678-tcp
    port: 5678
    protocol: TCP
    targetPort: 5678
  selector:
    name: {{ .Values.name }}
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}-webhook
    app.kubernetes.io/instance: {{ .Values.name }}-webhook
    app.kubernetes.io/part-of: {{ .Values.name }}-app
    template: {{ .Values.name }}-dc-template
  name: {{ .Values.name }}-webhook
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: 5678-tcp
    port: 5678
    protocol: TCP
    targetPort: 5678
  selector:
    name: {{ .Values.name }}-webhook
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}-worker
    app.kubernetes.io/instance: {{ .Values.name }}-worker
    app.kubernetes.io/part-of: {{ .Values.name }}-app
    template: {{ .Values.name }}-dc-template
  name: {{ .Values.name }}-worker
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: 5678-tcp
    port: 5678
    protocol: TCP
    targetPort: 5678
  selector:
    name: {{ .Values.name }}-worker
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/part-of: {{ .Values.name }}-app
    template: {{ .Values.name }}-dc-template
  name: postgresql-{{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: postgresql-{{ .Values.name }}
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/part-of: {{ .Values.name }}-app
    template: {{ .Values.name }}-dc-template
  name: redis-{{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: redis-{{ .Values.name }}
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis-{{ .Values.name }}
  sessionAffinity: None
  type: ClusterIP
