---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: n8n-hpa
objects:
  - kind: HorizontalPodAutoscaler
    apiVersion: autoscaling/v2
    metadata:
      name: "${NAME}-worker"
      namespace: "${NAMESPACE}"
      labels:
        app.kubernetes.io/part-of: "${NAME}-app"
    spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: "${NAME}-worker"
      minReplicas: 1
      maxReplicas: 3
      metrics:
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 75
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 75
  - kind: HorizontalPodAutoscaler
    apiVersion: autoscaling/v2
    metadata:
      name: "${NAME}-webhook"
      namespace: "${NAMESPACE}"
      labels:
        app.kubernetes.io/part-of: "${NAME}-app"
    spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: "${NAME}-webhook"
      minReplicas: 1
      maxReplicas: 3
      metrics:
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 75
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 75
parameters:
  - name: NAME
    value: n8n
  - name: NAMESPACE
    required: true

