---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: n8n-secrets
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      annotations:
        template.openshift.io/expose-username: "{.data[username]}"
        template.openshift.io/expose-password: "{.data[password]}"
        template.openshift.io/expose-encryption_key: "{.data[encryption-key]}"
      labels:
        template: "${NAME}-template"
        app.kubernetes.io/part-of: "${NAME}-app"
      name: "${NAME}"
      namespace: "${NAMESPACE}"
    stringData:
      username: "${N8N_USER}"
      password: "${N8N_PASSWORD}"
      encryption-key: "${N8N_ENCRYPTION_KEY}"
    type: Opaque
  - kind: Secret
    apiVersion: v1
    metadata:
      annotations:
        template.openshift.io/expose-database_name: "{.data['database-name']}"
        template.openshift.io/expose-password: "{.data['database-password']}"
        template.openshift.io/expose-username: "{.data['database-user']}"
      labels:
        template: "${NAME}-template"
        app.kubernetes.io/part-of: "${NAME}-app"
      app: "${NAME}"
      name: "postgresql-${NAME}"
      namespace: "${NAMESPACE}"
    stringData:
      database-name: "${NAME}"
      database-password: "${DATABASE_PASSWORD}"
      database-user: "${NAME}"
    type: Opaque
  - kind: Secret
    apiVersion: v1
    metadata:
      annotations:
        template.openshift.io/expose-password: "{.data['database-password']}"
      labels:
        template: "${NAME}-template"
        app.kubernetes.io/part-of: "${NAME}-app"
      name: "redis-${NAME}"
      namespace: "${NAMESPACE}"
    stringData:
      database-password: "${REDIS_DATABASE_PASSWORD}"
    type: Opaque
parameters:
  - name: NAME
    value: n8n
  - name: NAMESPACE
    required: true
  - name: N8N_USER
    value: n8n
  - name: N8N_PASSWORD
    displayName: N8N Password
    generate: expression
    from: "[a-zA-Z0-9]{16}"
  - name: N8N_ENCRYPTION_KEY
    displayName: N8N Encryption Key
    description: Auto-generated if not provided. WARNING - Do not change for existing installations!
    generate: expression
    from: "[a-zA-Z0-9]{8}!@#$%^&_[a-zA-Z0-9]{8}"
  - name: DATABASE_PASSWORD
    displayName: Database Password
    generate: expression
    from: "[a-zA-Z0-9]{16}"
  - name: REDIS_DATABASE_PASSWORD
    displayName: Redis Database Password
    generate: expression
    from: "[a-zA-Z0-9]{16}"

