# Manual started workflow
# This is the simplest for of running the Cypress tests in Github actions
name: artifactory-smoke
on: [workflow_dispatch, repository_dispatch]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      CYPRESS_username: ${{ secrets.CYPRESS_USER_NAME }}
      CYPRESS_password: ${{ secrets.CYPRESS_ARTIFACTORY_PW }}
      CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASEURL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Artifactory (CLAB) Smoke test
        uses: cypress-io/github-action@v5
        id: smoke
        # Continue the build in case of an error, as we need to set the
        # commit status in the next step, both in case of success and failure
        continue-on-error: true
        with:
          # No recording of results in the cloud
          record: false
          # We need to force the install due to version checking
          install-command: npm ci
          working-directory: testing
